#print("Hello World")
#print("First Program- Python print function")
#print('It is declared like this :')
#print("print('What to print')")
#input("What's your name ?\n")
#print("Hello"+" "+input("What Is Your Name="))

#print("Hey"+" "+input("What is your name?\n")+","+"How Are You?")
print("String Manipulation Exercise")
print("String Concatenation is Done With "+" Sign")
print('e.g. print("Hello"+"Jenny")')
print("New lines will be created with a backslash and n")